### ISSUE TITLE
Add addititonal field to the ShimConfigurator window where user can select the name for the created HadoopCluster

### ISSUE THREAD

**Issue by andreysanyuk** [Hramatskiu/shim-config-loader-start#1]
first in line =)

**Comment by Hramatskiu** [comment]
Field for NamedCluster name added. Commit - https://github.com/Hramatskiu/shim-config-loader-start/commit/96dc732c34fc6082cc1500b0972b0320a04f2678
Available in release - https://github.com/Hramatskiu/shim-config-loader-start/releases/tag/1.0.0
