### ISSUE TITLE
Some paths where configs are copied are incorrect

### ISSUE THREAD

**Issue by andreysanyuk** [Hramatskiu/shim-config-loader-start#6]
hbase-site.xml - should be copied only in shim folder
hive-site.xml - should be copied only in shim folder

**Comment by Hramatskiu** [comment]
Fixed with comment https://github.com/Hramatskiu/shim-config-loader-start/commit/5cad89929034633b1e6096d8a96e4175bdb2ef71 .
Release updated - 17.01.2018 https://github.com/Hramatskiu/shim-config-loader-start/releases/tag/1.0.0 .
